/**
 * The media of the site: generated by `npm run media` in the repo, in the
 * widths a page should offer.
 */

/** Width and height of every image as it was made. */
const SIZES: Record< number, [ number, number ] > = {
	1: [ 1600, 900 ],
	2: [ 1600, 1200 ],
	3: [ 1200, 1600 ],
	4: [ 1600, 900 ],
	5: [ 1400, 1400 ],
	6: [ 1600, 1000 ],
	7: [ 1600, 700 ],
	8: [ 1200, 1500 ],
};

const WIDTHS = [ 480, 720, 960, 1600 ];

/** What an `<img>` needs to load the right file and keep its place. */
export function image( n: number ) {
	const [ width, height ] = SIZES[ n ];
	return {
		src: `/media/${ n }-960.avif`,
		srcSet: WIDTHS.map(
			( to ) => `/media/${ n }-${ to }.avif ${ Math.min( to, width ) }w`
		).join( ', ' ),
		width,
		height,
	};
}

/** What a `<video>` needs. */
export const video = ( name: 'a' | 'b' ) => ( {
	src: `/media/${ name }.mp4`,
	poster: `/media/${ name }-poster.avif`,
	...( name === 'a'
		? { width: 1280, height: 720 }
		: { width: 960, height: 1200 } ),
} );
