/**
 * The media of the site: generated by `npm run media` in the repo, in the
 * widths a page should offer. Or, chosen at the top of the page, four
 * photos from Pexels in their place.
 */
import { useSyncExternalStore, type CSSProperties } from 'react';

/** What the pictures of the site are: colour fields, or photos. */
export type Kind = 'fields' | 'photos';

const KEY = 'gs-media';
let kind: Kind = 'fields';
try {
	kind = localStorage.getItem( KEY ) === 'photos' ? 'photos' : 'fields';
} catch {}
const hearing = new Set< () => void >();

/** The pictures the visitor has chosen. */
export const useKind = () =>
	useSyncExternalStore(
		( heard ) => {
			hearing.add( heard );
			return () => hearing.delete( heard );
		},
		() => kind,
		// The page as it is prerendered.
		(): Kind => 'fields'
	);

/** Chooses the pictures of the site, and keeps them for the next visit. */
export function choose( to: Kind ) {
	kind = to;
	try {
		localStorage.setItem( KEY, to );
	} catch {}
	hearing.forEach( ( heard ) => heard() );
}

/**
 * The photo in the place of an image or a film: four for eight, round
 * again. What each shows, what it is lit by, and the point of it that
 * stays in view when it is cut. From Pexels, 1600 px wide, as p1 to p4:
 * photos 8107912, 8112576, 6835833 and 5767690 of pexels.com/photo/.
 */
const PHOTOS = [
	{ alt: 'A woman in a leather jacket, sitting under a pink neon tube', light: '#d63bd6', focus: '30% 50%' },
	{ alt: 'A man kneeling by a boombox in front of neon signs', light: '#3f6df2', focus: '55% 45%' },
	{ alt: 'A woman in sunglasses between neon letters', light: '#16c8c0', focus: '45% 35%' },
	{ alt: 'A couple in an arcade, looking at the camera', light: '#c4e23c', focus: '72% 40%' },
];

// Which photo is in the place of which: chosen so that the sliders of
// the first page have no two alike side by side.
const PLACE: Record< number | 'a' | 'b', number > = {
	1: 1, 2: 2, 3: 3, 4: 4, 5: 2, 6: 3, 7: 1, 8: 4, a: 3, b: 2,
};

export const photo = ( n: number | 'a' | 'b' ) => PHOTOS[ PLACE[ n ] - 1 ];

/** Width and height of every image as it was made. */
const SIZES: Record< number, [ number, number ] > = {
	1: [ 1600, 900 ],
	2: [ 1600, 1200 ],
	3: [ 1200, 1600 ],
	4: [ 1600, 900 ],
	5: [ 1400, 1400 ],
	6: [ 1600, 1000 ],
	7: [ 1600, 700 ],
	8: [ 1200, 1500 ],
};

const WIDTHS = [ 480, 720, 960, 1600 ];

/**
 * The colour of every picture and film: what is most of all itself in it,
 * taken from the pictures, for the light a slide casts on the page.
 */
export const LIGHT: Record< number | 'a' | 'b', string > = {
	1: '#f35c6d',
	2: '#03bbf2',
	3: '#71f0cb',
	4: '#e54fb8',
	5: '#eaba34',
	6: '#8a6cf0',
	7: '#9ace5c',
	8: '#e0929e',
	a: '#6a3cf5',
	b: '#c0608f',
};

/** The light of a picture or film, of the pictures chosen. */
export const lightOf = ( n: number | 'a' | 'b', of: Kind ) =>
	of === 'photos' ? photo( n ).light : LIGHT[ n ];

/**
 * What an `<img>` needs to load the right file and keep its place; of a
 * photo, in the pictures that are photos, and of a film its photo.
 */
export function image( n: number | 'a' | 'b', of: Kind = 'fields' ) {
	if ( of === 'photos' ) {
		const name = `p${ PLACE[ n ] }`;
		return {
			src: `/media/${ name }-960.avif`,
			srcSet: WIDTHS.map(
				( to ) => `/media/${ name }-${ to }.avif ${ to }w`
			).join( ', ' ),
			width: 1600,
			height: 1067,
			style: { '--gs-focus': photo( n ).focus } as CSSProperties,
		};
	}
	const [ width, height ] = SIZES[ n as number ];
	return {
		src: `/media/${ n }-960.avif`,
		srcSet: WIDTHS.map(
			( to ) => `/media/${ n }-${ to }.avif ${ Math.min( to, width ) }w`
		).join( ', ' ),
		width,
		height,
	};
}

/**
 * The film of the pictures that are photos, in the place of `a`: video
 * 13794727 of Pexels, cut to a loop by `bin/make-film.mjs`. There is one,
 * so `b` is a photo there.
 */
export const FILM = 'Someone walking into a tunnel of coloured lights';

/** Whether there is a film of that name in the pictures chosen. */
export const filmed = ( name: 'a' | 'b', of: Kind = 'fields' ) =>
	of === 'fields' || name === 'a';

/** What a `<video>` needs. The films of the colour fields are made. */
export const video = ( name: 'a' | 'b', of: Kind = 'fields' ) => {
	const film = of === 'photos' && name === 'a';
	const file = film ? 'film' : name;
	const [ width, height ] = film
		? [ 960, 540 ]
		: name === 'a'
		? [ 1280, 720 ]
		: [ 960, 1200 ];
	return {
		src: `/media/${ file }.mp4`,
		poster: `/media/${ file }-poster.avif`,
		width,
		height,
	};
};
