import { chromium } from '@playwright/test';
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1280, height: 800 }, recordVideo: { dir: '/private/tmp/claude-502/-Users-niklas-code-shaderslide/58c9ddf0-8a26-4160-9922-0efe9a2f1c32/scratchpad/vid', size: { width: 1280, height: 800 } } });
const p = await c.newPage();
const errs = []; p.on('pageerror', e => errs.push(String(e))); p.on('console', m => m.type()==='error' && errs.push(m.text()));
await p.goto('http://localhost:5190' + process.argv[3]);
await p.waitForTimeout(2000);
const el = p.locator('#' + process.argv[2]); await el.scrollIntoViewIfNeeded();
const box = await el.boundingBox();
await p.mouse.move(box.x + box.width/2, box.y + box.height/2);
await p.waitForTimeout(1000);
await p.mouse.click(box.x + box.width/2, box.y + box.height/2);
await p.waitForTimeout(1200);
await p.keyboard.press('ArrowRight');
await p.waitForTimeout(1000);
await p.mouse.move(900, 400); await p.mouse.down(); await p.mouse.move(880, 400); await p.mouse.move(400, 400, { steps: 8 }); await p.mouse.up();
await p.waitForTimeout(1000);
await p.keyboard.press('Escape');
await p.waitForTimeout(1500);
console.log(errs.join('\n') || 'no errors');
await c.close(); await b.close();
